name: hachimie

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  pull-requests: write
  contents: read

jobs:
  # Biên dịch và Test
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew build

        # Lưu lại báo cáo test nếu bị lỗi để dễ dàng bắt bug
      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: mizu-test-reports
          path: build/reports/tests/
          retention-days: 5  
