name: hachimie

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  pull-requests: write
  contents: read

jobs:
  # Biên dịch và Test
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # Tạo file google-services.json giả lập để qua được bước kiểm tra của Google Services Plugin
      - name: Create dummy google-services.json
        run: |
          echo '{
            "project_info": {
              "project_number": "123456789",
              "project_id": "mock-project-id",
              "storage_bucket": "mock-bucket"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:123456789:android:123456789",
                  "android_client_info": {
                    "package_name": "com.example.shoeapp"
                  }
                },
                "oauth_client": [
                  {
                    "client_id": "123456789-mock-web-client-id.apps.googleusercontent.com",
                    "client_type": 3
                  }
                ],
                "api_key": [
                  {
                    "current_key": "mock-api-key"
                  }
                ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": []
                  }
                }
              }
            ],
            "configuration_version": "1"
          }' > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew build

        # Lưu lại báo cáo test nếu bị lỗi để dễ dàng bắt bug
      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: mizu-test-reports
          path: build/reports/tests/
          retention-days: 5  
